### ISSUE TITLE
Cannot sync or un-link board

### ISSUE THREAD

**Issue by leonardfactory** [oursky/Gitlo-Support#9]
Hello,

I just tried to link a board with a repo of mine. Now Gitlo says the board is linked, however whenever I try to use "Sync Now" it says "Synced", but nothing happens. If I try to reload the page, the status rollbacks to "Not Synced". Furthermore, I cannot unlink the board anymore. Am I doing something in the wrong way? Tell me if I can do something to isolate the problem.

Thanks!

**Comment by david90** [comment]
Hi leonard,

Thanks for using Gitlo!
It seems that you are not the admin of the repo. (If you are an admin, you can seeing a setting tab in the corresponding GitHub repo)

The repo is actually not linked and hence you can't unlink it.
You can try again with a repo that you own/ have admin right.

Cheers,
David

**Comment by leonardfactory** [comment]
Thank you, tried it as admin and it worked. Going to close this :+1:
